event_year: 2026
event_date_descr: November 7 & 8, 2026
event_date_descr_month_day: November 7 & 8

event_location_descr: Central Florida Fairgrounds & Expo Halls

contact_email: contact@robotruckus.org
